import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <nav className="flex items-center flex-1">
            <Link href="/" className="flex justify-between">Home</Link>
            <Link href="/" className="flex justify-between">About</Link>
            <Link href="/" className="flex justify-between">Container</Link>
            <Link href="/" className="flex justify-between">Contact</Link>
          </nav>
        </div>
        
        {children}</body>
    </html>
  );
}
